### ISSUE TITLE
bulk porting and style porting issue

### ISSUE THREAD

**Issue by tamilhighq** [h4lfheart/FortnitePorting#1]
1.please add an option to bulk import models like porting all models to selected folder.
2. importing styles for specific skins like memow skulls aurelian its exporting default skin instead of styles (basically cant export styles).
3. add an option to port poi and loading screens
4. Thanks ❤️

**Comment by h4lfheart** [comment]
1. no, bulk import doesn't fit with the scope of the program now that we're not dealing with file importing anymore
2. probably not because it's such a miniscule material feature but maybe
3. blenderumap exists for umaps and fmodel or umodel exist for general asset extraction

**Comment by h4lfheart** [comment]
though I might remove the disabling of the import button so exports can be added to a queue if that fits your "standard" for bulk exporting/importing

**Comment by tamilhighq** [comment]
thanks

**Comment by tamilhighq** [comment]
how to get styles for specific skins ?
