### ISSUE TITLE
Bundle Downloader Initialization failed...

### ISSUE THREAD

**Issue by diacoco** [h4lfheart/FortnitePorting#15]
Hello,

first of all, great work... this tool is just amazing!
It was forking fine until the "star wars update" i think, now, i have an error at startup when it tries to initialize the Bundle downloader...

2023-06-09 09:18:52.432 +02:00 [WRN] Failed to initialize Bundle Downloader, high resolution textures will not be downloaded

**Comment by Tevtongermany** [comment]
on which version are you?

**Comment by Tevtongermany** [comment]
if you are below 1.3 then get the updated version in the Fortnite porting server
and because of the new Fortnite version stuff has changed, and I am 80% certain that the porter broke because of the new Fortnite version
