### ISSUE TITLE
issue with to skin the texture doesn't work

### ISSUE THREAD

**Issue by RaptorDrama** [h4lfheart/FortnitePorting#18]
Hello, I have an issue with 2 skins the texture does not work when importing skins the texture does not work I try several methods but it does not work the 2 skins is  Lexa and Orin

**Comment by h4lfheart** [comment]
I am purposefully not supporting lexa and orin because their skins are ugly and their materials suck :)

**Comment by RaptorDrama** [comment]
ok no problem thanks for reply
