### ISSUE TITLE
Having a set up issue

### ISSUE THREAD

**Issue by ThePsyKai** [h4lfheart/FortnitePorting#2]
I run the FortnitePorting.exe and it does nothing. I have all the correct things installed for it.

**Comment by h4lfheart** [comment]
make sure you installed the desktop version of .net 6.0, then restart your computer and try again (https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime)
**
![image](https://user-images.githubusercontent.com/69497698/209236340-591d6855-047b-4b47-9325-9c685fa15a7e.png)
**
