### ISSUE TITLE
Can not access halfheart.dev from app

### ISSUE THREAD

**Issue by pto2k** [h4lfheart/FortnitePorting#20]
When I start FortnitePorting, it tries to access a few files from https://halfheart.dev/ and fails due to my network policy.
Would it be possible to pack these files with the release?
Or could I manually download them somewhere else and place them in the FP folder for the app to work?
Thanks!

**Comment by h4lfheart** [comment]
I'm afraid there's not really much I can do about that

technically they are all "optional" since it's just for updates, broadcasts, and a backup API but if those are failing, I have a feeling the other important apis and web requests will fail as well

**Comment by h4lfheart** [comment]
you can always try to disable windows defender or adjust your antivirus but if you've got restrictions out of your control, I really can't help at all
