### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by ilpiruz** [h4lfheart/FortnitePorting#25]
i get an error about "oo2core_9_win64.dll" missing

**Comment by h4lfheart** [comment]
update to latest

**Comment by ilpiruz** [comment]
what i need to update?
What i have already tried:
-installing x64 net redistributables
-installed vcredist, c++ redistributable
-updating fortniteporting to latest

**Comment by Ka1serM** [comment]
> what i need to update? 

FortnitePorting

**Comment by h4lfheart** [comment]
https://github.com/halfuwu/FortnitePorting/releases/tag/v1.5.5
