### ISSUE TITLE
Nice update, but still not perfect

### ISSUE THREAD

**Issue by ilpiruz** [h4lfheart/FortnitePorting#26]
Now it's working perfectly, but i still have an error when exporting music " Cannot start process because a file name has not been provided. "

**Comment by h4lfheart** [comment]
music packs are currently not supported because they now use binka encoding which is not supported yet.

**Comment by ilpiruz** [comment]
also if music isn't supported, is still a well made program and the dev did a perfect job

**Comment by ilpiruz** [comment]
does this affect emotes also?

**Comment by GhostScissors** [comment]
Anything  related to audio won't work
