### ISSUE TITLE
very bad bug

### ISSUE THREAD

**Issue by ilpiruz** [h4lfheart/FortnitePorting#28]
if you update, then accidentally delete everything that the program has made, then (in the next launch) it will throw thousand of errors and won't load anything

**Comment by h4lfheart** [comment]
what does this even mean, record a video or something lol

**Comment by ilpiruz** [comment]
i fixed everything, so i don't want to risk your app functionality.
what i did for make this bug happen:
1) use old .exe version
2) update to new 1.5.3  (1.5. i don't remember the third number)
3) delete the folder containing the .exe (and so, also assets of the app)
4) redownload program and run
5) console throws thousand of bugs

**Comment by h4lfheart** [comment]
can you show the errors i cant help otherwise

**Comment by ilpiruz** [comment]
"can you show the errors i cant help otherwise" i can't because i fixed it, but they were all about loading assets of fortnite, and something about wrong bools (-212312221)

**Comment by ilpiruz** [comment]
if you want, i can replicate it tho, the only thing is that probably it won't work again
