### ISSUE TITLE
Models not importing correctly (Blender 4.0)

### ISSUE THREAD

**Issue by NotBub** [h4lfheart/FortnitePorting#29]
The latest major release of Blender (Version 4.0 or newer) doesn't seem to import models correctly. Only the model's skeleton seems to import correctly. No errors appear in the console.

**Comment by h4lfheart** [comment]
yeah I'm aware of this, 4.0 support will be coming in FortnitePorting v2 (should release mid-late december)

**Comment by NotBub** [comment]
👍
