### ISSUE TITLE
emotes not loading

### ISSUE THREAD

**Issue by ilpiruz** [h4lfheart/FortnitePorting#31]
Idk if emotes are supported, but blender doesn't seem to load them

**Comment by h4lfheart** [comment]
you've gotta select an armature in blender, then import the emote. this will be more clear in v2

**Comment by ilpiruz** [comment]
thanks

**Comment by b1bradders** [comment]
> you've gotta select an armature in blender, then import the emote. this will be more clear in v2

Hiya, I've done that and the music gets added however no keyframes or animation is present upon pressing Spacebar (to start the animation/timeline)
I have an armature selected. Not sure what the issue is. It is a custom armature (ripped from the game 'Lethal Company') so I'm not sure if that's why it's not working?

**Comment by Ka1serM** [comment]
> > you've gotta select an armature in blender, then import the emote. this will be more clear in v2
> 
> 
> 
> Hiya, I've done that and the music gets added however no keyframes or animation is present upon pressing Spacebar (to start the animation/timeline)
> 
> I have an armature selected. Not sure what the issue is. It is a custom armature (ripped from the game 'Lethal Company') so I'm not sure if that's why it's not working?

Obviously Fortnite emotes will only import to a Fortnite armature. Keyframes won't show up because emotes are imported as NLA tracks👍

**Comment by ilpiruz** [comment]
what's NLA tracks?

**Comment by b1bradders** [comment]
> > > you've gotta select an armature in blender, then import the emote. this will be more clear in v2
> > 
> > 
> > Hiya, I've done that and the music gets added however no keyframes or animation is present upon pressing Spacebar (to start the animation/timeline)
> > I have an armature selected. Not sure what the issue is. It is a custom armature (ripped from the game 'Lethal Company') so I'm not sure if that's why it's not working?
> 
> Obviously Fortnite emotes will only import to a Fortnite armature.

Yeah, that makes sense. However, I thought this tool would have some kind of bone remap feature but oh well!

**Comment by h4lfheart** [comment]
that's what a animation retargeter is for, use rokoko or smth

**Comment by Bmarquez1997** [comment]
> > > > you've gotta select an armature in blender, then import the emote. this will be more clear in v2
> > > 
> > > 
> > > Hiya, I've done that and the music gets added however no keyframes or animation is present upon pressing Spacebar (to start the animation/timeline)
> > > I have an armature selected. Not sure what the issue is. It is a custom armature (ripped from the game 'Lethal Company') so I'm not sure if that's why it's not working?
> > 
> > 
> > Obviously Fortnite emotes will only import to a Fortnite armature.
> 
> Yeah, that makes sense. However, I thought this tool would have some kind of bone remap feature but oh well!

I've found this one to work quite well with the models exported by FortnitePorting, and much simpler to use than rokoko: https://github.com/Mwni/blender-animation-retargeting

**Comment by b1bradders** [comment]
> that's what a animation retargeter is for, use rokoko or smth

Yeah, I'm aware.
