### ISSUE TITLE
not exporting texture 

### ISSUE THREAD

**Issue by ilpiruz** [h4lfheart/FortnitePorting#32]
i tried importing kevin cube and got no texture at all, i tried any other thing and it correctly imported texture, but everytime you expport, the textures won't save in the file (tried obj, gltf, fbx) 
edit: nothing will work, anything will export as blank texture

**Comment by Th3Unkn0wns** [comment]
Kevin isn't supported and never will be.

**Comment by ilpiruz** [comment]
i know that kevin isn't supported (and please if you want, can you give me an explanation for it?)
but nothing exports textures to the file

**Comment by h4lfheart** [comment]
because Kevin uses a carry mat that cannot be generalized across most assets, it would require a complete recreation of the material node tree and that's just not possible for blender right now

**Comment by ilpiruz** [comment]
> because Kevin uses a carry mat that cannot be generalized across most assets, it would require a complete recreation of the material node tree and that's just not possible for blender right now

edit: i think i misspelled something: nothing works, anything (also the kevin cube)will export as blank texture
