### ISSUE TITLE
The app fails to install.

### ISSUE THREAD

**Issue by SappYoin** [h4lfheart/FortnitePorting#33]
After choosing how to set it up, it throws up this error.
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'Index')`

![image](https://github.com/halfuwu/FortnitePorting/assets/119620744/38dc5d95-2820-411f-806a-072a569768f3)

I'm on Windows 11, and have Blender 3.5, If it helps.

**Comment by h4lfheart** [comment]
update to latest
