### ISSUE TITLE
Playable and Exportable Jam Tracks/Jam Loops

### ISSUE THREAD

**Issue by b1bradders** [h4lfheart/FortnitePorting#39]
Hiya, I was looking for a way to play and/or export individual Jam Loops (drums, bass, lead, vocals) or just whole Jam Tracks. Is there a feature for this? If not, can this be added to, like, the Radio section or something?

Thanks in advance!

**Comment by h4lfheart** [comment]
they're not stored in games they're streamed from an API and I have no clue how it works

**Comment by b1bradders** [comment]
Ah okay, thanks! I did actually run a proxy on Fortnite once and I did see that. If you want, I could look into it and maybe make a PR for it eventually?

**Comment by h4lfheart** [comment]
I mean if you want to go for it

hmu on discord **@halfheart.** if you wanna send the API so I can implement it properly with the radio tab ty!!

**Comment by b1bradders** [comment]
Alright! Oh, and, I used to have Discord but I deleted my account ages ago and don't plan on returning to it. I'll just message you here :)

**Comment by b1bradders** [comment]
I see an API request go out to `https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game/spark-tracks` which seems to respond with every single Jam Track and includes the Track Name, each individual peice that makes it up (Lead, Vocals, etc.) and other stuff. It probably includes BPM aswell and the pitch. Take a look and see what you can figure out.

<img width="657" alt="Screenshot 2024-03-10 at 16 56 26" src="https://github.com/halfuwu/FortnitePorting/assets/69256931/91bbf6cb-7fcb-484e-94ff-2ae63c772d7c">

```
tt - Track Title
an - Author Name(?)
ry - Release Year
sn - Song Name

dn - Database Number(?)

sib - Song ??? Bass
sid - Song ??? Drum
sig - Song ??? ???
siv - Song ??? Vocals

mt - BPM value shown in Fortnite
mm - Major/Minor(?)

ar - The key/pitch it is in

mu - An unknown data file. It can't be related to the music data as it's only 300-900 KB in size

(?) = Unsure about this
??? = No Idea
```

**Comment by b1bradders** [comment]
Okay, so it gets URLs and stuff from here:
```
https://content-service.bfda.live.use1a.on.epicgames.com/api/content/v2/link/[song id]/cooked-content-package
```
Song ID is the value found in `jc` (see picture above).

So for winterfest wish, it's 1262-0193-4978.
For seven nation army, it's 9782-2337-8782.

It does seem that you need authorisation for those links. Not sure how you'd solve that.

**Comment by b1bradders** [comment]
And I'm not sure how it gets music data after that. I'm done proxying for the day though, but if you need some more info then just ask me and I'll dig some more tomorrow.

**Comment by Tevtongermany** [comment]
> And I'm not sure how it gets music data after that. I'm done proxying for the day though, but if you need some more info then just ask me and I'll dig some more tomorrow.

Ive did some digging with postman sending different requests and stuff including the 
`https://content-service.bfda.live.use1a.on.epicgames.com/api/content/v2/link/[song id]/cooked-content-package` one

so for auth it just uses a normal authentication
you need to have the user agent set as the game build rn its `Fortnite/++Fortnite+Release-29.01-CL-32291970 Windows/10.0.19042.1.768.64bit`
It also takes I think 2 parameters
1. platform
2. role
could also be more 
and this is the part where I couldn't dig any further since its just telling me this the whole time 
```
    "host": "content-service.bfda.live.use1a.on.epicgames.com",
    "method": "GET",
    "path": "/api/content/v2/link/1262-0193-4978/cooked-content-package",
    "errorCode": "errors.com.epicgames.content-service.forbidden",
    "errorMessage": "Missing required permission 'content-service:package READ' (aid=,cid=3446cd72694c4a4485d81b77adbb2141)"
}
```

**Comment by Tevtongermany** [comment]
And also the "mu" part of the request is an encrypted midi stated here https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/90ff2a11932c23e689551a591da1bd2f726223c6/EpicGames/FN-Content/Explanations/SparkTracks.md
