### ISSUE TITLE
TextureDecoder.DecodeTexture is a private static function not directly callable like this affecting compilation using the current CUE4Parse dependency

### ISSUE THREAD

**Issue by wywarren** [h4lfheart/FortnitePorting#49]
The function call here is affecting the solution compilation:
https://github.com/halfuwu/FortnitePorting/blob/f1bce8319d4379f993408469c84a9190a89803db/FortnitePorting/Extensions/ImageExtensions.cs#L28

I had to hack the dependency to public but it seems like the latest update is in their branch as public now:
https://github.com/FabianFG/CUE4Parse/blob/4e955153559be8dc156d15fc93ff8c1016d3ebfe/CUE4Parse-Conversion/Textures/TextureDecoder.cs#L126

Not sure if there needs to be additional dependency updates to be addressed for this.

**Comment by h4lfheart** [comment]
it's not, pull latest cue4parse

will push submodule update later
