### ISSUE TITLE
is this a virus

### ISSUE THREAD

**Issue by very-spiffy** [h4lfheart/FortnitePorting#51]
I put the exe file through virustotal it marked it as malicious. Is this a bug or is it a virus?

**Comment by h4lfheart** [comment]
it's not a virus!!! I mean you can compile the source code yourself but it's not malicious, just a false positive

**Comment by very-spiffy** [comment]
how do i compile the source code?

**Comment by h4lfheart** [comment]
google it.

**Comment by very-spiffy** [comment]
how to compile source code?
