### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by very-spiffy** [h4lfheart/FortnitePorting#56]
The Modular Mountain Gallery Lava Buildable doesn't have any textures.

**Comment by Tevtongermany** [comment]
you would need to get them yourself files tab prolly

**Comment by very-spiffy** [comment]
what do you mean?

**Comment by Tevtongermany** [comment]
you need to export them manually if they are not present in the shading tab
and please just ask in the discord server for problems! not on github issues

**Comment by very-spiffy** [comment]
Alright
