### ISSUE TITLE
Emote Import Bug

### ISSUE THREAD

**Issue by Mozart-Neighbor** [h4lfheart/FortnitePorting#57]
Hi, as the title suggests, importing emotes messes with the skeleton for some female skins (i.e. Echo), like the shoulders get in a really high and unnatural position for the whole duration of the emote, and this counts for the majority if not all the emotes (I've tried around 150).
I've also tried messing with the export settings with no avail, changing the rig type doesn't do much and there is no option to choose between type CLM/CMF (like with PSA) to check if either works differently from the other, or maybe it's there and I just didn't see it.       XD
Now, I only started using blender around a week ago so I know this might not be an issue actually worth reporting cause the solution is under my nose and I'm too stupid to smell it or something, but I'd really appreciate an answer that would at least partially explain what a possible solution could be (possibly without flaming my noob ass too much).
Cheers

**Comment by reversalss** [comment]
There is a [thread](https://discord.com/channels/866821077769781249/1249309074903007242/1249309674444951563) in the Discord server explaining solutions to this problem, it pretty much boils down to either:
1. finding the female version of the animations in the file tab (you can hover the emote to see its codename) then search for that in the files tab and adding either CMF or CLM depending on if its a large skin or a normal one. An example would be: EID_Griddles_CMF

2. Selecting every bone except for the pelvis and root bones, then removing and visually resetting all their location keyframes

**Comment by Mozart-Neighbor** [comment]
> There is a [thread](https://discord.com/channels/866821077769781249/1249309074903007242/1249309674444951563) in the Discord server explaining solutions to this problem, it pretty much boils down to either:
> 1. finding the female version of the animations in the file tab (you can hover the emote to see its codename) then search for that in the files tab and adding either CMF or CLM depending on if its a large skin or a normal one. An example would be: EID_Griddles_CMF
> 
> 2. Selecting every bone except for the pelvis and root bones, then removing and visually resetting all their location keyframes

Thanks for such a quick response, I'll check out both solutions ASAP and join the discord server for eventual issues I might run into :)

p.s. I'll leave the issue open until I solve it, just in case.

Edit: Just tried both methods and they work perfectly, thanks again.
