### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Parsa307** [h4lfheart/FortnitePorting#6]
The following blender object(s) contain special characters or a white space in the name(s):
"M_MED_Headset_FaceAcc_LOD0.mo","M_MED_Headset_Head_LOD0.mo","M_MED_Headset_LOD0.mo","M_MED_Headset_FaceAcc_LOD0.ao","M_MED_Headset_Head_LOD0.ao","M_MED_Headset_LOD0.ao"
Note: the only valid special characters are "+", "-" and "_".

**Comment by h4lfheart** [comment]
This is a "bug" with another plugin and is out of my control. Just rename the objects to fit the criteria.
