### ISSUE TITLE
Model not inserting

### ISSUE THREAD

**Issue by yyarchii** [h4lfheart/FortnitePorting#60]
Anytime I try to insert a model, it only makes a collection, not the actual model or pose. Is this a porting issue or is it my blender/pc? Could you help me with this?

**Comment by Skye732** [comment]
After updating FP to v 2.1.10 I had the same issue as well. I found out that in the plugins tab my version of Blender wasn't linked. After relinking I am getting the asset imported again and not just empty collection.

**Comment by yyarchii** [comment]
> After updating FP to v 2.1.10 I had the same issue as well. I found out that in the plugins tab my version of Blender wasn't linked. After relinking I am getting the asset imported again and not just empty collection.

Thank you! It works for me now.
