### ISSUE TITLE
After a couple of seconds it gives an error and doesn't work after multiple tries and a blender/computer restart

### ISSUE THREAD

**Issue by BoyOHBoy123** [h4lfheart/FortnitePorting#8]
System.Collections.Generic.KeyNotFoundException: There is no game file with the path "/plugins/fortnitegame/content/content/balance/raritydata.uasset"

**Comment by h4lfheart** [comment]
update your game

**Comment by BoyOHBoy123** [comment]
There is no update, so I can't

**Comment by BoyOHBoy123** [comment]
what you should of said was update Fortnite Porting, cuz that worked 🤓
